python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A man and woman sitting at a table on the beach"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A group of tents are set up in the woods"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A man and woman sitting at a table with drinks"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A girl with long hair and green eyes stands in front of a tree"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A boat is in the water near a rocky mountain"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A man and woman sitting at a table with drinks"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A man and woman sitting at a table on the beach"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A boat is in the water near a rocky mountain"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A man and woman sitting at a table by the water"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A yellow and black bird flying through a blue sky"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A little girl in a wheelchair with a toy"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A group of women holding signs in front of a crowd"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A tall tower with a clock on top"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A man in a suit and tie is talking to a woman"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "Get that superheroie by the - girl"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A woman in a black dress and glasses is on the news"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A woman in a bikini is talking to a man"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A bunch of bottles of liquor on a shelf"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A close up of a camera with a pen on it"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A person holding a white card with a black and white pattern"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A doll is standing on a bed"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "Blur of a person walking"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A group of people are gathered around a tree"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A woman is sitting down on the news"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A group of people walking around a street"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A man in a blue shirt is standing next to a motorcycle"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A person is putting a bag of food into a box"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A person walking in the snow near a fence"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A white plate with the words news brief on it"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A man in a hat and a baseball cap"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A white microwave oven"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A white pot and a silver spoon on a table"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A bunch of books on a table"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "The adobe file in adobe"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A table with bowls of food and a bowl of food"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A bowl filled with food sitting on top of a table"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A bunch of plastic bags sitting on top of a table"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A bunch of plastic bags sitting on top of a table"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "Two dolls are sitting in a hospital bed"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A doll is sitting on a chair"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A flooded street in the suburbs of detroit, michigan"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A small white mouse is sitting on the floor"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A cat is sitting on the floor next to a bottle of liquid"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A baseball player is being hit by a umpire"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A cartoon character holding a white cat"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A cartoon character holding a white cat"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A cat is sitting on the floor next to a bottle of liquid"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A snow covered parking lot"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A snow covered parking lot with a sign"
python /workspace/CogVideoX-Fun/examples/cogvideox_fun/predict_t2v.py --prompt "A flooded street in phoenix, arizona"