python /workspace/EasyAnimate/predict_t2v.py --prompt "A man and woman sitting at a table on the beach. A woman sitting at a table with a drink"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A group of tents are set up in the woods. A bird flying over the water at sunset"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A man and woman sitting at a table with drinks. A woman in a bikini is standing on the beach"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A girl with long hair and green eyes stands in front of a tree. A painting of a forest with trees and grass"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A boat is in the water near a rocky mountain. A woman sitting at a table with a drink"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A man and woman sitting at a table with drinks. A man and woman sitting at a table on the beach"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A man and woman sitting at a table on the beach. A woman sitting at a table with a drink"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A boat is in the water near a rocky mountain. A woman sitting at a table with a drink"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A man and woman sitting at a table by the water. A woman in a bikini sitting on a beach"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A yellow and black bird flying through a blue sky. The girls of the twilight"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A little girl in a wheelchair with a toy. A doll sitting in a chair next to a box"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A group of women holding signs in front of a crowd. A man and woman are standing in front of a microphone"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A tall tower with a clock on top. A man is putting his ballot in the ballot box"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A man in a suit and tie is talking to a woman. A man in a suit and tie is talking to another man in a suit"
python /workspace/EasyAnimate/predict_t2v.py --prompt "Get that superheroie by the - girl. File file for you png file for you my little pony"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A woman in a black dress and glasses is on the news. A woman sitting on a couch in front of a tv screen"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A woman in a bikini is talking to a man. A man and woman sitting at a table with drinks"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A bunch of bottles of liquor on a shelf. A man is standing at the bar"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A close up of a camera with a pen on it. A man standing in front of a motorcycle"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A person holding a white card with a black and white pattern. A man is holding a cell phone"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A doll is standing on a bed. A little girl is putting a gift box"
python /workspace/EasyAnimate/predict_t2v.py --prompt "Blur of a person walking. A purple vase with a white flower on it"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A group of people are gathered around a tree. A cat is standing in the dark"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A woman is sitting down on the news. Two women sitting on a couch talking to each other women"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A group of people walking around a street. A woman walking down a street with a blue jacket"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A man in a blue shirt is standing next to a motorcycle. A close up of a cell phone"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A person is putting a bag of food into a box. A person is putting food into a container"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A person walking in the snow near a fence. A black background with a white and red flower"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A white plate with the words news brief on it. A woman standing in front of a brick wall"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A man in a hat and a baseball cap. Police investigates a man who was shot in the back of a car in the river"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A white microwave oven. A white bowl with a spoon and a cup"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A white pot and a silver spoon on a table. A white crocked pot"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A bunch of books on a table. A table with a bunch of boxes of food"
python /workspace/EasyAnimate/predict_t2v.py --prompt "The adobe file in adobe. A computer screen with a green background"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A table with bowls of food and a bowl of food. Ingredients for making a cake"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A bowl filled with food sitting on top of a table. A white cup with a spoon in it"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A bunch of plastic bags sitting on top of a table. A pile of plastic bags"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A bunch of plastic bags sitting on top of a table. A pile of plastic bags"
python /workspace/EasyAnimate/predict_t2v.py --prompt "Two dolls are sitting in a hospital bed. Two dolls sitting on a chair"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A doll is sitting on a chair. A doll with glasses on sitting in a chair"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A flooded street in the suburbs of detroit, michigan. A dog is standing in the middle of a flooded street"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A small white mouse is sitting on the floor. A small dog is sitting on the floor"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A cat is sitting on the floor next to a bottle of liquid. A small white mouse"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A baseball player is being hit by a umpire. A baseball player is about to catch the ball"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A cartoon character holding a white cat. A cartoon character with a blue background"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A cartoon character holding a white cat. A cartoon character with a blue background"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A cat is sitting on the floor next to a bottle of liquid. A cat is sitting on the floor next to a bottle of sauce"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A snow covered parking lot. A black background with a white and red flower"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A snow covered parking lot with a sign. A black background with a white and red flower"
python /workspace/EasyAnimate/predict_t2v.py --prompt "A flooded street in phoenix, arizona. A police tape is taped around a wall that was covered with graffiti"